### ISSUE TITLE
Woothee::OS can accept nil?

### ISSUE THREAD

**Issue by mtgto** [woothee/woothee-ruby#23]
In rails, `request.user_agent` is nullable if there is no `User-Agent` header in request.
I found methods of `Woothee::OS` does not check user-agent is nil or not.

```console
> Woothee::OS.challenge_smartphone(nil, {})
NoMethodError: undefined method `index' for nil:NilClass
```

#4 says `Woothee.parse` can accept nil

```console
Woothee.parse(nil)
=> {:name=>"UNKNOWN", :category=>"UNKNOWN", :os=>"UNKNOWN", :os_version=>"UNKNOWN", :version=>"UNKNOWN", :vendor=>"UNKNOWN"}
```

IMO, `Woothee::OS` should accept nullable user agent string.
If you think so, I will create a pull request.

**Comment by tagomoris** [comment]
`challenge_x` methods are only for internal use, not public APIs (it's not documented in README).
How the `result` hash values (2nd argument) are updated depends on the implementation, and I don't want to maintain the compatibility of such behaviors.

**Comment by mtgto** [comment]
Thanks for your quick reply.
I'll try to use public API or check nil before call `Woothee::OS` methods.

**Comment by tagomoris** [comment]
Thanks for understanding.
JFYI: "os" fields will be updated not only by `OS.challenge_*` methods (for example, Japanese cellar phones, Playstation, etc)
