### ISSUE TITLE
Is woothee-ruby licensed under MIT License or Apache License V2?

### ISSUE THREAD

**Issue by yujideveloper** [woothee/woothee-ruby#29]
`License.txt` says MIT License, but the License section of `README.md` says Apache License V2.
Which license is correct?

https://github.com/woothee/woothee-ruby/blob/c28b9d16f2a29ca85b82a5135c0a299016f56f64/LICENSE.txt#L3
https://github.com/woothee/woothee-ruby/blob/c28b9d16f2a29ca85b82a5135c0a299016f56f64/README.md#L71

**Comment by tagomoris** [comment]
Oops, LICENSE.txt was generated by `bundle gem` automatically, unintentionally. My intention is to apply Apache-2.0.
I'll update those.

**Comment by tagomoris** [comment]
I've updated the license displays.
@yujideveloper Thank you for pointing it!
