### ISSUE TITLE
Why isn't VALUE_UNKNOWN symbol

### ISSUE THREAD

**Issue by osdakira** [woothee/woothee-ruby#7]
I expect that `Woothee.parse(user_agent)[:category]` returns some `symbol`.

When user_agent is unknown, it returns `string`.

https://github.com/woothee/woothee-ruby/blob/master/lib/woothee.rb#L153
```rb
Woothee::ATTRIBUTE_CATEGORY => Woothee::VALUE_UNKNOWN,
```

https://github.com/woothee/woothee-ruby/blob/master/lib/woothee/dataset.rb#L30
```rb
VALUE_UNKNOWN = "UNKNOWN"
```

`VALUE_UNKNOW` is `string`.

Could you change `VALUE_UNKNOWN` from `string` to `symbol`?

**Comment by tagomoris** [comment]
Hmm, it's better to add `CATEGORY_UNKNOWN = :UNKNOWN` for unknown categories.

All values of Woothee are string. It's the basic rule of all woothee implementations.
So I cannot change `VALUE_UNKNOWN` from string to symbol.

Patches are welcome :)

**Comment by osdakira** [comment]
Oh, it's basic rule.
I got it!
Thank you for reply.
